name: Build CI

on:
  push:
    branches: ["main", "backend-dev", "frontend-dev", "mobile-dev"]
  pull_request:
    branches: ["main", "backend-dev", "frontend-dev", "mobile-dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm run install:all

      - name: Build project
        run: npm run build --if-present
