name: Frontend Tests

on:
  push:
    branches: ["main", "frontend-dev"]
  pull_request:
    branches: ["main", "frontend-dev"]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install frontend dependencies
        run: npm install --prefix frontend

      - name: Run frontend tests
        run: npm test --prefix frontend --if-present
